#!/usr/bin/env node

var Library = require("./Library");
var Player  = require('./Player');
var charm   = require('charm')();
var blessed = require('blessed');
var _       = require('lodash');

charm.pipe(process.stdout);
library = new Library(function() {
  player  = new Player(function() {

  });
});
